language: php
php:
  - 5.4
  - hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
 # hhvm ignores sendmail_path and hhvm.mail.sendmail_path settings presently...
 - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then sudo ln -s /bin/true /usr/local/bin/sendmail; fi
 - composer global require drush/drush:6.*
 - export PATH="$HOME/.composer/vendor/bin:$PATH"
 - phpenv rehash
 - drush make --concurrency=5 build-lightning.make lightning
 - cd lightning
 - drush si lightning --db-url=mysql://root:@localhost/drupal --yes
 - echo '$base_url = "http://127.0.0.1:8080";' >> sites/default/settings.php
 - drush en composer_manager -y
 - drush en behatrunner -y
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4

script: drush brun --uri=http://127.0.0.1:8080 --verbose

matrix:
  allow_failures:
    - php: hhvm

notifications:
  slack:
    rooms:
      - acquia:KkTwsMNJshR8hV4VvPbZs2J8#lightning
