language: php
cache:
  bundler: true
  apt: true
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
sudo: false
install:
- composer self-update
- composer --version
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:7.*
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- cd ..
- drush make --concurrency=5 lightning/drupal-org-core.make drupal -y
- mkdir drupal/profiles/lightning
- cp -R lightning/* drupal/profiles/lightning/.
- cd drupal
- drush make --concurrency=5 profiles/lightning/drupal-org.make --no-core --contrib-destination=profiles/lightning  -y
- drush si lightning --db-url=mysql://root:@localhost/drupal -y
before_script:
- drush runserver --server=builtin 8080 &>/dev/null &
script:
- drush le lightning_demo
notifications:
  slack:
    secure: TdpsXHDERsAzIGHgzgdodKrz+Tlr0oaHz8REaYKASH3l55/fEw3OA2F7iuLTtyeN9wUmBbm3m1TfvMRdVwxYvEX0XIEW4eN8cJJZGjSjsGjuqh5N/842ou9Fn3hxpJZLw4eNrZeY4DtzNWIi2+rBIjWYBGNYlJxh0NLOYVrpZLZi+44yQ4aWUx0hXXK4H+1bb87FHCOtGd7fvkuEGAJxKBJ2VMiVpc7jP4acLhRdu8Wv0A7OxAoTZwOPZekB9K73N/FLbDZf2xlD/Oachyvbt43r4FuBuMO6kNE0+HoOt09E6F9LfsHKHeZ3WRRgZMi9KN/LUU3N/N5AulPcIkCmccaI6C/UwvRfHYTsdAP2qA7eRmLoy1VsGcm0DCVVRCE5eL2ydjm3sP/t/WxTSXtUHV2nPAhx9vk4FlZeskDWbnyaNQ+uCtN3ekhl7amrSxGWydJPiM+cETr8xogsQZHrCH9F67Nzohrlh+YL9XzqROsop2vJbu5dONxOivriYu2EBe+i+78uEi/BK0YGNxDO8Ix/kB5f9Bmbo5g5weOsnRYzDCG1JMiAkPwKP1zn9pS13CIBfS5utgzSzWljCgZPRtPVmAztEs6ITqVQbOiuRYu3mSA+KsyFuB4I5/pm+h1Vh9h1kS89Hs2ftrkYboMkqzQBrYo1Jru6CRxnKb8OCFY=
matrix:
  fast_finish: true
