language: php

cache:
  bundler: true
  apt: true
  directories:
    - vendor

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Run environmental updates
  - sudo apt-get update > /dev/null
  # Update composer
  - composer selfupdate
  # Configure MySQL for Drupal
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
  # Configure php.ini settings
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  # Install Drush 6
  - composer global require drush/drush:6.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Build the profile, preserving current state
  - cd ..
  - drush make --concurrency=5 lightning/drupal-org-core.make drupal -y
  - mkdir drupal/profiles/lightning
  - cp -R lightning/* drupal/profiles/lightning/.
  - cd drupal
  - drush make --concurrency=5 profiles/lightning/drupal-org.make --no-core --contrib-destination=profiles/lightning -y

before_script:
  # Install Drupal
  - drush si lightning --db-url=mysql://root:@localhost/drupal -yvd
  # Disable dblog to reduce MySQL load
  - drush dis dblog -yvd
  # Enable Composer Manager and BehatRunner
  - drush en composer_manager -yvd
  - drush en behatrunner -l http://127.0.0.1:8080 -yvd
  # Clear caches
  - drush cc all
  # Run the lightweight http server
  - drush runserver --server=builtin 8080 &
  - sleep 4

script:
  # Run any module provided Behat tests
  - drush brun -l http://127.0.0.1:8080 -vd

notifications:
  slack:
    rooms:
      - acquia:KkTwsMNJshR8hV4VvPbZs2J8#lightning

matrix:
  fast_finish: true

after_failure:
  - sudo chmod -Rv 777 build/logs/*
  - bundle install --without development
  - travis-artifacts upload --path build/logs --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
